name: CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1) Install pnpm FIRST so setup-node's cache logic can find it
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      # 2) Then setup Node with pnpm cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Sanity versions
        run: |
          node -v
          pnpm -v
          which pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile || pnpm install

      - name: Generate Prisma Client
        run: pnpm exec prisma generate

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          CI: "1"
        run: pnpm build

      - name: Smoke test
        run: |
          pnpm dev & DEV=$!
          sleep 2
          curl -sI http://localhost:3000 | head -n1
          kill $DEV || true